// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkxxznclupatcdpjrgwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxreHh6bmNsdXBhdGNkcGpyZ3d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyOTY1MjcsImV4cCI6MjA2NDg3MjUyN30.mIVg9EPQFJxCSzAzJ35Y4o5YogIXYc65kDXXGx_SAy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);